name: BetsGalore
favicon: null
layout_spectrum: 0.31269847764633596
typography_spectrum: 0.15776
title: "Ireland's Premier Tipping Site"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ba160c'
    - '#111c3c'
    - '#77ac1c'
    - '#bccdd4'
    - '#b16458'
  brandStrength: 0.7528116304893047
  lightness: 0.1771536241285503
  saturation: 0.028376983711495996
  rhythmicContrast: 0.75
purpose: []
