title: "Ireland's Premier Tipping Site"
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.3125
  rhythmicContrast: 0.75
  brandColors:
    - '#010101'
    - '#b9957b'
    - '#4a403e'
    - '#afc0c8'
    - '#b2231b'
  lightness: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: BetsGalore
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.15776
layout_spectrum: 0.5967742
