name: BetsGalore
favicon: null
layout_spectrum: 0.31269847764633596
typography_spectrum: 0.15776
title: "Ireland's Premier Tipping Site"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#b9957b'
    - '#4a403e'
    - '#afc0c8'
    - '#b2231b'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.028376983711495996
  rhythmicContrast: 0.75
purpose: []
